server:
  port: 8080
  servlet:
    context-path: /cxk
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://101.200.48.39:3306/db_cxk?characterEncoding=utf8&useSSL=true
    username: cxkuser
    password: cxk@123
  profiles:
    active: dev
#logging:
#  level:
#    org.springframework.web: debug